
project_id = "hkvjdxxndapxpslovrlc"

[functions.check-missing-launches]
verify_jwt = false

[calendar.check-missing-launches]
schedule = "0 1 * * *"  # Executar todos os dias à 01:00

[functions.check-missing-attendance]
verify_jwt = false

[functions.enviar-alerta-falta-webhook]
verify_jwt = false

[functions.test-slack-message]
verify_jwt = false

[functions.enviarMensagemSlack]
verify_jwt = false

[functions.check-hibernating-cards]
verify_jwt = false

[calendar.check-hibernating-cards]
schedule = "0 3 * * *"  # Executar todos os dias às 03:00

